alias g='git'
alias sl='ls'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias duf='du -sk | sort -n | perl -ne '\''($s,$f)=split(m{\t});for (qw(K M G)) {if($s<1024) {printf("%.1f",$s);print "$_\t$f"; last};$s=$s/1024}'\'
alias jcurl='curl -v -H "Accept: application/json" -H "Content-type: application/json" -b .cookies -c .cookies'
alias susp='dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend'
alias hib='dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Hibernate'
alias neo='setxkbmap de neo -option'
alias de='setxkbmap de'
alias us='setxkbmap us'
alias tubvpn='sudo openconnect vpn.tu-berlin.de --script  /etc/vpnc/vpnc-script'
alias banot='ssh alu7053@banot.etsii.ull.es'
alias clip='xsel -b'
alias j='jobs'
alias h='history'
alias nonose='nosetests --nocapture --nologcapture'
alias wifioff='nmcli nm wifi off'
alias wifion='nmcli nm wifi on'
alias anaconda='source ~/Apps/anaconda/bin/activate normal'
alias deactivate='source ~/Apps/anaconda/bin/deactivate'
alias disablenmnotifications='gsettings set org.gnome.nm-applet disable-disconnected-notifications "true"; gsettings set org.gnome.nm-applet disable-connected-notifications "true"'
alias enablenmnotifications='gsettings set org.gnome.nm-applet disable-disconnected-notifications "true"; gsettings set org.gnome.nm-applet disable-connected-notifications "true"'
alias scan='nmap -sP 192.168.178.255/24'
alias wifiscan='sudo iwlist wlan1 scan'
alias invert='xcalib -invert -alter'
alias ap='sudo aptitude'
alias timelapse='mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell:autoaspect:vqscale=3 -vf scale=1920:1080 -mf type=jpeg:fps=25 mf://@gopro.txt -o gopro.mp4'
alias addaudio='mencoder gopro.mp4 -o gopro_music.mp4 -ovc copy -oac copy -audiofile '
alias rocketdbssh='ssh -fqN om_user@db1.rocket-om.com -L 5432:127.0.0.1:5432'
alias lock='gnome-screensaver-command -l'
alias coffeer='coffee -cwo'
alias fontsize='printf '"'"'\33]50;%s%d\007'"'"' "xft:Inconsolata for Powerline:pixelsize="'
alias vodafone-stick="sudo usb_modeswitch -v 0x19d2 -p 0x2000 -V 0x19d2 -P 0x0031 -m 0x01 -M 55534243123456782000000080000c85010101180101010101000000000000"
# use like 'create_ctags <tagsfile> <code_dir>'
alias ctags_create='ctags -R --sort=yes --c++-kinds=+p --fields=+ilaS --extra=+q --language-force=C++ -f '
alias tmoteserial='java net.tinyos.tools.PrintfClient -comm serial@/dev/ttyUSB0:115200'
alias tmoteserial2='java net.tinyos.tools.PrintfClient -comm serial@/dev/ttyUSB1:115200'
alias tmoteserial3='java net.tinyos.tools.PrintfClient -comm serial@/dev/ttyUSB2:115200'
