setlocal tabstop=4
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal noexpandtab
setlocal autoindent
setlocal smarttab
setlocal errorformat=%f:%l:%c:\%m
setlocal makeprg=make
setlocal makeef=/tmp/vim##.err
